config/routes.rb
Giftr::Application.routes.draw do

  root to: "static_pages#home"

  devise_for :users, :path => "accounts", 
                     :path_names => { :sign_in => "login", 
                                      :sign_out => "logout", 
                                      :sign_up => "register" }

  resources :users do
    resource :profile
  end

  resources :memberships, :only => [:create]
  resources :exchanges do
      post :make_matches, :on => :member
      resources :gifts, :only => [:index], :on => :member do 
        post :add_gift, :on => :member
      end
  end

  resources :gift_ideas, :only => [:index, :create, :destroy]

  put "/accept/:id", to: "invitations#accept_invite", :as => :accept 
  put "/deny/:id", to: "invitations#deny_invite", :as => :deny

  get "/contact", to: "static_pages#contact"
  get "/faq", to: "static_pages#faq"

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :address, :city, :fname, :lname, :phone, :state, :zip, :user_id

  belongs_to :user

  [ :user_id,
    :fname,
    :lname].each{|field| validates field,
                                :presence => true}
                                
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_profile_exists, :only => [:show]
  before_filter :check_profile_owner, :except => [:new, :create]
  
  def new
    @profile = current_user.build_profile()
  end

  def create
    @profile = current_user.build_profile(params[:profile])
    if @profile.save
      flash[:success] = "Profile created"
      redirect_to user_profile_path(current_user)
    else
      render 'new'
    end
  end

  def show
      @profile = Profile.find_by_user_id(params[:user_id])
      @old_notifications = @profile.user.old_notifications
      @new_notifications = @profile.user.new_notifications
  end

  def edit
    @profile = Profile.find_by_user_id(current_user.id)
  end

  def update
    @profile = Profile.find_by_user_id(current_user.id)
    if @profile.update_attributes(params[:profile])
      flash[:success] = "Profile updated"
      redirect_to user_profile_path(current_user)
    else 
      render 'edit'
    end
  end

  private

  # If a user creates an account and closes browser before
  # creating a profile, they need to create one before
  # they can use the service

  def check_profile_exists
    profile = Profile.find_by_user_id(current_user.id)

    # If profile is not found it will be set to nil and this will redirect to creating a profile
    unless profile 
      redirect_to new_user_profile_path()
    end
  end

  def check_profile_owner
    profile = Profile.find_by_user_id(current_user.id)
    unless profile.user_id == current_user.id
      redirect_to new_user_profile_path()
    end
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def profile_owner?(profile)
     profile.user_id == current_user.id
    #   return true
    # else
    #   return false
    # end
  end
end

app/views/profiles/edit.html.erb
<h2>Edit your giftSpork Profile</h2>
<%= form_for(@profile, 
             :url => user_profile_path(current_user)) do |f| -%>
  <%= render "shared/error_messages", object: @profile %>
  <br>
  <%= f.label :fname, "First Name" %>
  <%= f.text_field :fname %>
  <br>
  <%= f.label :lname, "Last Name" %>
  <%= f.text_field :lname %>
  <br>
  <%= f.submit "Update Profile" %> 
<% end %>

app/views/profiles/new.html.erb
<h2>Create Your giftSpork Profile</h2>
<%= form_for(@profile, 
             :url => user_profile_path(current_user)) do |f| -%>
  <%= render "shared/error_messages", object: @profile %>
  <%= f.label :fname, "First Name" %>
  <%= f.text_field :fname %>
  <%= f.label :lname, "Last Name" %>
  <%= f.text_field :lname %>
  <%= f.submit "Create Profile" %> 
<% end %>

app/views/profiles/show.html.erb
<% if profile_owner?(@profile) %>
  <br>
  <div class="sidebar clearfix">
    <% if current_user.new_invitations.any? %>
      <div id="invitations-box" class="well">
        <h3>New Invitations</h3>
        <%= render partial: "invitations/invitation",
                   collection: current_user.new_invitations,
                   :as => :invitation %>
      </div>
    <% end %>

    <div id="organized-box" class="well">
      <h3>Exchanges Organized</h3>
      <%= render current_user.organized_exchanges %>
    </div>

    <div id="participating-box" class="well">
      <h3>Exchanges Joined</h3>
      <%= render current_user.participations %>
    </div>
  </div>

  <div>
    <h1>Hi <%= @profile.fname %>!</h1>
  </div>

  <br>
  <%= link_to "Create New Exchange!", new_exchange_path, 
      :class => "btn btn-primary btn-large" %>

  <div>
    <% if current_user.gift_ideas.any? %>
    <h3>Your Gift Ideas</h3>
    <div class="masonry-container">
      <%= render partial: "gift_ideas/gift_idea", 
                 collection: current_user.gift_ideas %>
    <% end %>
  </div>

  <%# link_to "All Exchanges",  exchanges_path%>

<% else %>
  Not authorized to view someone else's profile
<% end %>

<script type="text/javascript">

    var $container = $('.masonry-container');

    $container.imagesLoaded(function() {
      $container.masonry({
        itemSelector: '.gift-brick:visible',
        isAnimated: true,
      });
    });

</script>

<!-- After accepting an invite (e.g creating a membership) I will have an after_create callback on the membership look up which invitation that membership is associated with and update accepted to true

On declining an invite I will have a json request to update the invitation accepted to false. I will have an after_update callback on the invitation to mark the associated notification. 

Also have a js listener on all links in the invite to check if there are more unseen notifications -->