config/routes.rb
Giftr::Application.routes.draw do

  root to: "static_pages#home"

  devise_for :users, :path => "accounts", 
                     :path_names => { :sign_in => "login", 
                                      :sign_out => "logout", 
                                      :sign_up => "register" }

  resources :users do
    resource :profile
  end

  resources :memberships, :only => [:create]
  resources :exchanges do
      post :make_matches, :on => :member
      resources :gifts, :only => [:index], :on => :member do 
        post :add_gift, :on => :member
      end
  end

  resources :gift_ideas, :only => [:index, :create, :destroy]

  put "/accept/:id", to: "invitations#accept_invite", :as => :accept 
  put "/deny/:id", to: "invitations#deny_invite", :as => :deny

  get "/contact", to: "static_pages#contact"
  get "/faq", to: "static_pages#faq"

end

app/models/exchange.rb
class Exchange < ActiveRecord::Base
  attr_accessible :exchange_date, :match_date, :name, :max_price, :organizer_id, :matchedup, :invitations_attributes, :description
  
  ############# Associations ##################

  has_many :invitations, 
           :inverse_of => :exchange,
           :dependent => :destroy

  accepts_nested_attributes_for :invitations,
                                :reject_if => :all_blank

  belongs_to :organizer, 
             :foreign_key => :organizer_id,
             :class_name => "User"

  has_many :memberships, :dependent => :destroy, 
           :inverse_of => :exchange
  
  has_many :participants, 
           :through => :memberships, 
           :source => :user

  has_many :matches, 
           :dependent => :destroy

  has_many :gifts, 
           :through => :matches

  has_many :gift_ideas,
           :dependent => :destroy

  ############ Validations ####################

  [ 
    :organizer_id,
    :exchange_date,
    :match_date,
    :name,
    :max_price].each{|field| validates field,
                                :presence => true}
  
  validate :match_date_at_least_a_week_away, :on => :create
  validate :updated_match_date_must_be_tomorrow_or_later, 
           :on => :update
  validate :exchange_date_at_least_three_days_after_match_date
  validate :invitations_count

  # Custom Validators
  def match_date_at_least_a_week_away
    unless match_date >= (Date.today + 7.days)
      errors.add(:match_date, "must be at least a week away")
    end
  end

  def exchange_date_at_least_three_days_after_match_date
    unless exchange_date >= (match_date + 3.days)
      errors.add(:exchange_date, "must be at least 3 days after match date to give people a chance to find gifts.")
    end
  end

  def invitations_count
    errors.add(:invitations, "You need at least one other person to exchange gifts with.") if invitations.empty?
  end

  # On update they will be able to make the match date be earlier
  # But 3 days before match, Exchange will lock so no further updates
  def updated_match_date_must_be_tomorrow_or_later
    unless match_date > Date.today
      errors.add(:match_date, "must be set to tomorrow or later")
    end
  end

  ############ Custom Queries ####################

  def get_participant_names
     self.participants.joins(:profile).select('fname, lname')
  end

  # Will do this in gifts controller when I add in ETSY api
  def gifts_below_max_price
    Gift.find_by_sql(["SELECT gifts.* FROM gifts WHERE gifts.price <= :max_price", :max_price => self.max_price])
  end

  def invites_outstanding
    invitations.where('accepted is NULL')
  end

  ############ Constructors ####################

  def make_santas
    if matchedup
      raise "Already Matched Up"
    end
    
    ps = participants.shuffle

    ps.each_with_index do |participant, i|

      matches.build(:santa_id => participant.id,
                    :recipient_id => ps[(i+1)%ps.length].id)

    end
    self.matchedup = true
    unless save
      raise errors.full_messages
    end
  end

end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_participant, :only => [:show]

  def new
    @exchange = Exchange.new()
    3.times { @exchange.invitations.build }
  end

  def create
    @exchange = Exchange.new(params[:exchange])
    @exchange.organizer_id = current_user.id
    @exchange.max_price *= 100

    # The creator of the exchange sends out the invitations
    @exchange.invitations.each do |invitation|
      invitation.sender_id = current_user.id
    end

    # The organizer is also the first member 
    @exchange.memberships.build(user_id:current_user.id)

    if @exchange.save
      flash[:success] = "Exchange created!"
      @exchange.invitations.each do |invitation|
        if invitation.is_registered?
          # They have an account, so send an invitation email and create a new notification
          InvitationMailer.notify_of_invitation(invitation,new_user_session_url).deliver

          # Notifies the invite recipient internally
          Notification.create(:associated_id => invitation.id,
                              :user_id => User.find_by_email(invitation.invited_email).id,
                              :kind => "invite")
        else
          # They don't have an account yet.  Just send email, notification will be created on signup
          InvitationMailer.invite_to_service(invitation, new_user_registration_url(:invitation_id => invitation.token)).deliver
        end
      end
      redirect_to exchange_path(@exchange.id)
    else
      if @exchange.invitations.count < 3
        3.times { @exchange.invitations.build }
      end
      render 'new'
    end
  end

  def show
    @exchange = Exchange.find(params[:id])
    @organizer = @exchange.organizer
    @organizer_profile = @organizer.profile
    @participant_names = @exchange.get_participant_names
    if @exchange.matchedup
      @current_match = @exchange.matches.where('santa_id = :user_id', :user_id => current_user.id)
      @current_recipient = @current_match.first.recipient 
      @current_recipient_profile = @current_recipient.profile
      @current_gift = @current_match.first.gift
    end
  end

  def edit
    @exchange = Exchange.find(params[:id])
  end

  def update
    @exchange = Exchange.find(params[:id])
    if @exchange.update_attributes(params[:exchange])
      flash[:success] = "Exchange updated!"
      redirect_to exchange_path(@exchange)
    else
      render 'edit'
    end
  end

  def destroy
    @exchange = Exchange.find(params[:id])
    @exchange.destroy
    redirect_to user_profile_path(current_user)
  end

  def make_matches
    exchange = Exchange.find_by_id(params[:id])
    begin
      exchange.make_santas
    rescue Exception => e
      flash[:error] = e.to_s
      redirect_to exchange_path(exchange)
    else
      flash[:success] = "Participants successfully matched!"
      redirect_to exchange_path(exchange)
    end
  end

  def index
    @exchanges = Exchange.all
    @currently_participating = current_user.participations
    @new_exchanges = @exchanges - @currently_participating
  end

  private


  # Makes sure a user is a participant or organizer of exchange they try to view
  def check_participant
    begin
      exchange = Exchange.find(params[:id])

    # If record is not found it will redirect back to profile
    rescue ActiveRecord::RecordNotFound
      if signed_in?
        redirect_to user_profile_path(current_user)
      else
        # Unecessary check because this is already checked for by :authenticate_user!
        redirect_to root_path
      end
    end

    if exchange
      unless exchange.participants.map{|p| p.id}.include?(current_user.id)
         redirect_to user_profile_path(current_user)
      end
    end
  end

end

app/helpers/exchanges_helper.rb
module ExchangesHelper
  # REV: I'd pass in the exchange; otherwise this method doesn't
  # really do that much.
  def is_organizer?(organizer)
     organizer.id == current_user.id
  end
end

app/views/exchanges/_exchange.html.erb
<p><%= link_to exchange.name, exchange_path(exchange) %></p>

app/views/exchanges/_form.html.erb
<%# Decides whether submit button says create or update %>
<% if @exchange.id.nil? %>
  <% verb = "Create" %>
<% else %>
  <% verb = "Update" %>
<% end %>

<%= form_for @exchange do |f| -%>
  <%= render "shared/error_messages", object: @exchange %>
  <%= f.label :name, "Exchange Name" %>
  <%= f.text_field :name %>
  <%= f.label :description, "Description of Exchange" %>
  <%= f.text_area :description,  :cols => "30", :rows => "5"%>
  <%= f.label :match_date, "Invitation Acceptance Deadline" %>
  <%= f.date_select :match_date %>
  <%= f.label :exchange_date, "Date of Exchange (or Shipping Deadline)" %>
  <%= f.date_select :exchange_date %>
  <br>
  <%= f.label :price, "Max Price Participants Can Spend" %>
  <%= f.text_field :max_price %>
  <br>
  <% if verb == "Create" %>
    <b>Invite People To Your Exchange via Email</b>
    <br>
    <%= f.fields_for(:invitations) do |invitation_form| %>
      <%= invitation_form.label :invited_email, "Email:" %>
      <%= invitation_form.text_field :invited_email %>
      <br>
    <% end %>
  <% end %>
  <%= f.submit "#{verb} Exchange", :class => "btn btn-primary" %>
<% end -%>

app/views/exchanges/edit.html.erb
<%= link_to "Delete Exchange", exchange_path(@exchange), :method => :delete, :data => {:confirm => "Not in a giving mood any more?"}, :class => "btn btn-danger btn-large big-delete" %>
<%= render "form" %>
<%= link_to "Cancel", exchange_path(@exchange) %>
<script type="text/javascript">
$(function(){
  var $maxPrice = $('input#exchange_max_price')
  var formatted_value = ($maxPrice.val()/100).toFixed(2);
  $maxPrice.val(formatted_value);
});
</script>

app/views/exchanges/index.html.erb
<% @exchanges.each do |exchange|  %>
<!-- REV: use your exchange partial -->
<h3><%= exchange.name %>
<!-- REV: view helper method -->
<% if exchange.organizer_id == current_user.id %>
*
<% end %>
</h3>
<!-- REV: should probably be in a styled UL. This is really hard to
     read with this indenting. -->
<!-- REV: why is *everything* in a span? -->
<span><b>Match Date:</b> <%= exchange.match_date %></span><br>
<span><b>Exchange Date:</b> <%= exchange.exchange_date %></span><br>
<span><b>Max Gift Price:</b> <%= change_to_dollars(exchange.max_price) %></span><br>

<!-- REV: use whitespace judiciously. Break this from the preceding, separate concern. -->
<!-- REV: another opportunity for a helper
<% if @new_exchanges.include?(exchange) %>
<span><%= link_to "Join Exchange", memberships_path(:exchange_id => "#{exchange.id}"), :method => :post %></span><br>
<% else %>
<span><%= link_to "Already Participant", exchange_path(exchange) %></span>
<% end %>
<br>
<% end %>

app/views/exchanges/new.html.erb
<%= render "form" %>
<%= link_to "Cancel", user_profile_path(current_user) %>
<script type="text/javascript">
$(function(){
  var $maxPrice = $('input#exchange_max_price')
  var formatted_value = ($maxPrice.val()/100).toFixed(2);
  $maxPrice.val(formatted_value);
});
</script>

app/views/exchanges/show.html.erb
<div id="exchange-info-box" class="well">
  <h3>Exchange Info</h3>
    <p>Exchange: <i> <%= @exchange.name %></i></p>
    <p>Max Gift Price: <%= change_to_dollars(@exchange.max_price) %></p>
    <% if is_organizer?(@organizer) %>   
      <% unless @exchange.matchedup %>
        <%= link_to "Edit Exchange", edit_exchange_path(@exchange) %>
        <br>
        <br>
        <%= link_to "Match Everyone Now!", make_matches_exchange_path, :method => :post, :class => "btn btn-info", :data => { :confirm => "Are you sure?  You can't invite more people or edit the exchange after matching." } %>
      <% end %>
    <% end %>
  <br>
</div>

<h1><%= @exchange.name %> </h1>
<h2>
    Organized By: 
    <%= @organizer_profile.fname %> <%= @organizer_profile.lname %>
</h2>
<p><i>
  <%= @exchange.description %>
</i>
</p>

<h3>My Match:</h3>

<% if @exchange.matchedup %>
  <h4><%= @current_recipient_profile.fname %> 
  <%= @current_recipient_profile.lname %>
  </h4>

  <% if @current_match.first.gift_id %>
    <div class = "giftbox">
      <%= @current_gift.name %><br>
      Price: <%= change_to_dollars(@current_gift.price) %><br>
      <img src= <%= @current_gift.picture_url %> ><br>
      <%= link_to "Change Gift", exchange_gifts_path(@exchange) %> 
    </div>
  <% else %>
    <span>You haven't gotten your match a gift yet.</span><br>
    <%= link_to "Click to find a gift", exchange_gifts_path(@exchange) %>
  <% end %>

<% else %>
  <h4><i><%= distance_of_time_in_words(Time.now, @exchange.match_date.midnight) %> until matching</i></h4>
  <p><%= link_to "Look for gift ideas", 
         exchange_gifts_path(@exchange) %></p>
<% end %>

<h3>Participants: </h3>
<ul>
  <% @participant_names.each do |user_obj| %>
      <li><%= user_obj.fname%> <%= user_obj.lname %></li>
    <% end %>
</ul>

<% unless @exchange.matchedup %>
  <% if is_organizer?(@organizer) %>
    <h3>Still Waiting to Hear From <%= pluralize(@exchange.invites_outstanding.count, 'Person') %>:</h3>
    <ul>
      <% @exchange.invites_outstanding.each do |invite| %>
      <li><%= invite.invited_email %></li>
      <% end %>
    </ul>
  <% else %>
    <h3><%= @exchange.invites_outstanding.count %> More Invited </h3>
  <% end %>
<% end %>