config/routes.rb
Giftr::Application.routes.draw do

  root to: "static_pages#home"

  devise_for :users, :path => "accounts", 
                     :path_names => { :sign_in => "login", 
                                      :sign_out => "logout", 
                                      :sign_up => "register" }

  resources :users do
    resource :profile
  end

  resources :memberships, :only => [:create]
  resources :exchanges do
      post :make_matches, :on => :member
      resources :gifts, :only => [:index], :on => :member do 
        post :add_gift, :on => :member
      end
  end

  resources :gift_ideas, :only => [:index, :create, :destroy]

  put "/accept/:id", to: "invitations#accept_invite", :as => :accept 
  put "/deny/:id", to: "invitations#deny_invite", :as => :deny

  get "/contact", to: "static_pages#contact"
  get "/faq", to: "static_pages#faq"

end

app/models/gift.rb
class Gift < ActiveRecord::Base
  attr_accessible :category, :color, :name, :picture_url, :price

  has_many :matches

  # REV: throw some validations in.
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  require 'addressable/uri'

  def index
    @exchange = Exchange.find(params[:exchange_id])
    @current_gift = current_user.gift_on_current_exchange(@exchange).first
    @gift_ideas = current_user.gift_ideas_for_exchange(@exchange)
    @etsy_search_results = get_all_listings_for_price(@exchange.max_price/100)["results"]
    @etsy_gifts = Kaminari.paginate_array(@etsy_search_results).page(params[:page]).per(9)
  end

private

  def get_all_listings_for_price(max_price)
    listings_url = Addressable::URI.new(
      :scheme => "http",
      :host => "openapi.etsy.com",
      :path => "/v2/listings/active",
      :query_values => {
        :api_key => "8kbw5yv1l9lheqod41k3la5r",
        :includes => "MainImage(url_170x135)",
        :fields => "listing_id,title,url,price",
        :max_price => "#{max_price}",
        :limit => "100"
      }
      ).to_s

    final_listings = JSON.parse(RestClient.get(listings_url))

    final_listings
  end

end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/views/gifts/_etsy_gift.html.erb
<div class="giftbox gift-brick"
  data-gifturl="<%= gift["url"] %>"
  data-giftid="<%= gift["listing_id"] %>"
  data-image="<%= gift["MainImage"]["url_170x135"] %>"
  data-name="<%= gift["title"].split[0..3].join(" ") %>"
  data-price="<%= gift["price"] %>" >
  <img src=<%= gift["MainImage"]["url_170x135"] %> ><br>
  <div class="gift-info">
    <b><a style="color:white" href="<%= gift["url"] %>" target="_blank"><%= raw(gift["title"].split[0..3].join(" ")) %></a></b><br>
    Price: <%= gift["price"] %>   
  </div>
</div>

app/views/gifts/_gift.html.erb
<div class="giftItem">
  <div class="imgbox">
    <img src= <%= gift.picture_url %> >
  </div>
  <div class="frameBottom">
    <p><b><% gift.name %></b></p>
  </div> 
</div>

app/views/gifts/index.html.erb
<h2>Gift Ideas For 
    <i><%= link_to @exchange.name, exchange_path(@exchange) %></i>
</h2>
<div class="clearfix">
  <div class="shopping-sidebar">
    <p><b>Drag Gift Ideas Here</b></p>
    <ul>
      <!-- drag gift ideas here or have them populate from prev-->
      <% if @gift_ideas.any? %>
        <%= render partial: "gift_ideas/gift_idea_list_item",
                   collection: @gift_ideas,
                   :as => :giftidea %>
      <% end %>
    </ul>
  </div>
  <div id="paginator">
    <%= paginate @etsy_gifts, :remote => true %>
  </div>
  <div class="masonry-container">
      <%= render partial: "gifts/etsy_gift",
                 collection: @etsy_gifts,
                 :as => :gift %>
  </div>
</div>

<script>
  $(function(){
    /* MASONRY FUNCTIONS */
    // Must remain in view because otherwise there are refresh errors

    var $container = $('.masonry-container');

    // Load first group of images into masonry
    $container.imagesLoaded(function() {
      $container.masonry({
        itemSelector: '.gift-brick:visible',
        isAnimated: true,
        columnWidth: 35
      });
    });

    // Removes item from screen and reloads masonry
    function removeItem($masonTbl, $item){
      $masonTbl.masonry('remove', $item).masonry('reload');
    };

    /* JQUERY UI FUNCTIONS */
    // Need to remain in view to pass erb elements to javascript

    // Make gift brick dragabble 
    $(".gift-brick").draggable({
      revert: "invalid",
      containment: "document"
    });

    
    // When gift brick is dropped into sidebar, keep it there and update the gift-idea model
    $(".shopping-sidebar").droppable({
      drop: function(e, ui){
        var ondrop = GI.postGiftIdea(ui.draggable,
                                    <%= current_user.id %>,
                                    <%= @exchange.id %>,
                                    $container)

        ondrop.fail(function(response){
          console.log("Fail");
          removeItem($container, ui.draggable)
        });

        ondrop.always(function(response){
          console.log("post was attempted");
        });
      }
    });

    /* ALL OTHER JS THIS VIEW IN assets/javascripts/gifts.js*/
    GI.start(); 
  })
</script>

app/views/gifts/index.js.erb
// Renders the newest page of results and when clicking a paginated link and binds all the necessary masonry and jquery ui functionality to the new elements on the screen

$(function(){
  var $container = $('.masonry-container');

  $container.html('<%= escape_javascript(render partial:"gifts/etsy_gift", collection: @etsy_gifts, :as => :gift) %>');
  $('#paginator').html('<%= escape_javascript(paginate(@etsy_gifts, :remote => true).to_s) %>');

  $container.masonry('reload');

  // Load images into masonry
  $container.imagesLoaded(function() {
    $container.masonry({
      itemSelector: '.gift-brick:visible',
      isAnimated: true,
      columnWidth: 35
    });
  });

  // Removes item from screen and reloads masonry
  function removeItem($masonTbl, $item){
    $masonTbl.masonry('remove', $item).masonry('reload');
  };

// Make gift brick dragabble 
  $(".gift-brick").draggable({
    revert: "invalid",
    containment: "document"
  });

    
  // When gift brick is dropped into sidebar, keep it there and update the gift-idea model
  $(".shopping-sidebar").droppable({
    drop: function(e, ui){
      var ondrop = GI.postGiftIdea(ui.draggable,
                                  <%= current_user.id %>,
                                  <%= @exchange.id %>,
                                  $container)

      ondrop.fail(function(response){
        console.log("Fail");
        removeItem($container, ui.draggable)
      });

      ondrop.always(function(response){
        console.log("post was attempted");
      });
    }
  });
});