config/routes.rb
Giftr::Application.routes.draw do

  root to: "static_pages#home"

  devise_for :users, :path => "accounts", 
                     :path_names => { :sign_in => "login", 
                                      :sign_out => "logout", 
                                      :sign_up => "register" }

  resources :users do
    resource :profile
  end

  resources :memberships, :only => [:create]
  resources :exchanges do
      post :make_matches, :on => :member
      resources :gifts, :only => [:index], :on => :member do 
        post :add_gift, :on => :member
      end
  end

  resources :gift_ideas, :only => [:index, :create, :destroy]

  put "/accept/:id", to: "invitations#accept_invite", :as => :accept 
  put "/deny/:id", to: "invitations#deny_invite", :as => :deny

  get "/contact", to: "static_pages#contact"
  get "/faq", to: "static_pages#faq"

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "giftSpork", root_path, :class => 'brand' %>
<a class="brand brand-logo" href = "#"></a>
<ul class="nav pull-right">
  <% if user_signed_in? %>
    <li>
      <%= link_to current_user.profile.fname, user_profile_path(current_user) %>
    </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        My Settings
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to 'Profile Settings', edit_user_profile_path(current_user)%>
        </li>
        <li>
          <%= link_to 'Account Settings', edit_user_registration_path %>
        </li>
      </ul>
    </li>
  <% else %>
    <li>
      <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
      <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
      <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>giftspork</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="my-main">
  <div class="navbar navbar-inverse">
    <nav class="navbar-inner">
      <div class="container-fluid">
        <%= render 'layouts/navigation' %>
      </div><!--/.nav-collapse -->
    </nav>
  </div>
  <div id="main" class="container clearfix">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>

</div>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>giftspork</title>
  <%= stylesheet_link_tag "static_pages", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse">
    <nav class="navbar-inner">
      <div class="container-fluid">
        <%= render 'layouts/navigation' %>
      </div><!--/.nav-collapse -->
    </nav>
  </div>    
  <%= yield %>
  <%# debug(params) if Rails.env.development? %>
</body>
</html>